/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import app.controller.OrderController;
import app.controller.OrderItemsController;
import app.controller.ProductController;
import app.controller.UserController;
import app.services.ProductsDao;
import app.services.UsersDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Order;
import models.OrderItems;
import models.Product;
import models.User;

/**
 *
 * @author RIDHO
 */
public class DashboardAdmin extends javax.swing.JPanel {

    /**
     * Creates new form dashboard
     */
    public DashboardAdmin() {
        initComponents();
    }

    private void loadRiwayatStok() {
        try {
            List<Product> products = productcont.getAllProducts();

            DefaultTableModel model = (DefaultTableModel) jTableRiwatStok.getModel();
            model.setRowCount(0);

            for (Product p : products) {
                model.addRow(new Object[]{
                    p.getProduct_id(),
                    p.getProduct_name(),
                    p.getPrice(),
                    p.getStock(),
                    p.getUpdated_at()
                });

                totalProduct += 1;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTotalPesanan() {
        try {
            List<Order> orderlist = ordercont.getAllOrders();

            for (Order object : orderlist) {
                List<OrderItems> orderitemlist = orderitemcont.getItemsByOrderId(object.getOrder_id());

                for (OrderItems orderItems : orderitemlist) {
                    totalOrderItems += orderItems.getQuantity();
                }
                totalOrder += 1;
            }
        } catch (Exception ex) {
            System.getLogger(DashboardAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    private void loadTotalUser() {
        try {
            List<User> userlist = usercont.getAllUsers();

            for (User user : userlist) {
                totalUser += 1;
            }
        } catch (Exception ex) {
            System.getLogger(DashboardAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    OrderController ordercont = OrderController.getInstance();
    ProductController productcont = ProductController.getInstance();
    UserController usercont = UserController.getInstance();
    OrderItemsController orderitemcont = OrderItemsController.getInstance();

    Integer totalUser = 0;
    Integer totalProduct = 0;
    Integer totalOrderItems = 0;
    Integer totalOrder = 0;

    public void LoadData() {
        totalUser = 0;
        totalProduct = 0;
        totalOrderItems = 0;
        totalOrder = 0;

        loadRiwayatStok();
        loadTotalPesanan();
        loadTotalUser();

        lblTotalPesanan.setText(totalOrder.toString());
        lblTotalUser.setText(totalUser.toString());
        lblOrderItem.setText(totalOrderItems.toString());
        lblTotalProduk.setText(totalProduct.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlTotalPesan = new javax.swing.JPanel();
        lblTotalPesanan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlTotalproduk = new javax.swing.JPanel();
        lblTotalProduk = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlStokProduk = new javax.swing.JPanel();
        lblOrderItem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRiwatStok = new javax.swing.JTable();
        jLabelRiwayat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalUser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard Admin");

        lblTotalPesanan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalPesanan.setText("50");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Total Orders");

        javax.swing.GroupLayout pnlTotalPesanLayout = new javax.swing.GroupLayout(pnlTotalPesan);
        pnlTotalPesan.setLayout(pnlTotalPesanLayout);
        pnlTotalPesanLayout.setHorizontalGroup(
            pnlTotalPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalPesanLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlTotalPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        pnlTotalPesanLayout.setVerticalGroup(
            pnlTotalPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalPesanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPesanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTotalProduk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalProduk.setText("20");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Total Products");

        javax.swing.GroupLayout pnlTotalprodukLayout = new javax.swing.GroupLayout(pnlTotalproduk);
        pnlTotalproduk.setLayout(pnlTotalprodukLayout);
        pnlTotalprodukLayout.setHorizontalGroup(
            pnlTotalprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalprodukLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlTotalprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        pnlTotalprodukLayout.setVerticalGroup(
            pnlTotalprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalprodukLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalProduk)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        lblOrderItem.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblOrderItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOrderItem.setText("10");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Total Ordered Items");

        javax.swing.GroupLayout pnlStokProdukLayout = new javax.swing.GroupLayout(pnlStokProduk);
        pnlStokProduk.setLayout(pnlStokProdukLayout);
        pnlStokProdukLayout.setHorizontalGroup(
            pnlStokProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStokProdukLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlStokProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOrderItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        pnlStokProdukLayout.setVerticalGroup(
            pnlStokProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStokProdukLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrderItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableRiwatStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "Stok", "Updated At"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRiwatStok.setFocusable(false);
        jTableRiwatStok.setRowHeight(40);
        jScrollPane1.setViewportView(jTableRiwatStok);

        jLabelRiwayat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRiwayat.setText("History Product");

        lblTotalUser.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalUser.setText("15");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Total User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addComponent(jLabelRiwayat)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlTotalPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlTotalproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlStokProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTotalproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTotalPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStokProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jLabelRiwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelRiwayat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRiwatStok;
    private javax.swing.JLabel lblOrderItem;
    private javax.swing.JLabel lblTotalPesanan;
    private javax.swing.JLabel lblTotalProduk;
    private javax.swing.JLabel lblTotalUser;
    private javax.swing.JPanel pnlStokProduk;
    private javax.swing.JPanel pnlTotalPesan;
    private javax.swing.JPanel pnlTotalproduk;
    // End of variables declaration//GEN-END:variables
}
