/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import app.controller.UserController;
import app.services.ProductsDao;
import app.services.UsersDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Product;
import models.User;

/**
 *
 * @author RIDHO
 */
public class DashboardAdmin extends javax.swing.JPanel {

    /**
     * Creates new form dashboard
     */
    public DashboardAdmin() {
        initComponents();
        loadDashboardData();
        loadRiwayatStok();
        loadTotalUser();
//        loadTotalPesanan();
    }

    private void loadDashboardData() {
        try {
            ProductsDao productDao = new ProductsDao();

            int totalProduk = productDao.getAll().size();

            int totalStok = 0;
            for (Product p : productDao.getAll()) {
                totalStok += p.getStock();
            }

            jTotalProduk.setText(String.valueOf(totalProduk));
            jLabelStokProduk.setText(String.valueOf(totalStok));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTotalUser() {
        try {
            UserController userController = UserController.getInstance();
            List<User> users = userController.getAllUsers();

            jLabel3.setText(String.valueOf(users.size()));

        } catch (Exception e) {
            jLabel3.setText("Total User: ERROR");
        }
    }

//    private void loadTotalPesanan() {
//        try {
//            OrdersDao orderDao = new OrdersDao();
//            List<Order> orders = orderDao.getAll();
//
//            jLabelTotalPesanan.setText(String.valueOf(orders.size()));
//
//        } catch (Exception e) {
//            jLabelTotalPesanan.setText("Total Pesanan: 0");
//        }
//    }
    private void loadRiwayatStok() {
        try {
            ProductsDao productDao = new ProductsDao();
            List<Product> products = productDao.getAll();

            DefaultTableModel model = (DefaultTableModel) jTableRiwatStok.getModel();
            model.setRowCount(0);

            for (Product p : products) {
                model.addRow(new Object[]{
                    p.getProduct_id(),
                    p.getProduct_name(),
                    p.getPrice(),
                    p.getStock(),
                    p.getUpdated_at()
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlTotalPesan = new javax.swing.JPanel();
        jLabelTotalPesanan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlTotalproduk = new javax.swing.JPanel();
        jTotalProduk = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlStokProduk = new javax.swing.JPanel();
        jLabelStokProduk = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRiwatStok = new javax.swing.JTable();
        jLabelRiwayat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard Admin");

        jLabelTotalPesanan.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabelTotalPesanan.setText("50");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Total Pesanan ");

        javax.swing.GroupLayout pnlTotalPesanLayout = new javax.swing.GroupLayout(pnlTotalPesan);
        pnlTotalPesan.setLayout(pnlTotalPesanLayout);
        pnlTotalPesanLayout.setHorizontalGroup(
            pnlTotalPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalPesanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlTotalPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelTotalPesanan))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlTotalPesanLayout.setVerticalGroup(
            pnlTotalPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalPesanLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotalPesanan)
                .addGap(49, 49, 49))
        );

        jTotalProduk.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jTotalProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTotalProduk.setText("20");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Total Produk");

        javax.swing.GroupLayout pnlTotalprodukLayout = new javax.swing.GroupLayout(pnlTotalproduk);
        pnlTotalproduk.setLayout(pnlTotalprodukLayout);
        pnlTotalprodukLayout.setHorizontalGroup(
            pnlTotalprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalprodukLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlTotalprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTotalProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlTotalprodukLayout.setVerticalGroup(
            pnlTotalprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalprodukLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTotalProduk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelStokProduk.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabelStokProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelStokProduk.setText("10");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Stok Produk");

        javax.swing.GroupLayout pnlStokProdukLayout = new javax.swing.GroupLayout(pnlStokProduk);
        pnlStokProduk.setLayout(pnlStokProdukLayout);
        pnlStokProdukLayout.setHorizontalGroup(
            pnlStokProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStokProdukLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlStokProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStokProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlStokProdukLayout.setVerticalGroup(
            pnlStokProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStokProdukLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStokProduk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableRiwatStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "Stok", "Updated At"
            }
        ));
        jTableRiwatStok.setFocusable(false);
        jTableRiwatStok.setRowHeight(40);
        jScrollPane1.setViewportView(jTableRiwatStok);

        jLabelRiwayat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRiwayat.setText("Riwayat Produk");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("15");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Total User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRiwayat)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pnlTotalPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pnlTotalproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pnlStokProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 341, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTotalPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTotalproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStokProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRiwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelRiwayat;
    private javax.swing.JLabel jLabelStokProduk;
    private javax.swing.JLabel jLabelTotalPesanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRiwatStok;
    private javax.swing.JLabel jTotalProduk;
    private javax.swing.JPanel pnlStokProduk;
    private javax.swing.JPanel pnlTotalPesan;
    private javax.swing.JPanel pnlTotalproduk;
    // End of variables declaration//GEN-END:variables
}
