/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import app.controller.CartController;
import app.controller.CartItemsController;
import app.controller.OrderController;
import app.controller.OrderItemsController;
import app.controller.PaymentController;
import app.controller.ProductController;
import app.controller.UserController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import models.Cart;
import models.CartItem;
import models.Order;
import models.Payment;
import models.Product;
import models.User;
import paymentfactory.PaymentFactory;
import ui.KF;

/**
 *
 * @author RIDHO
 */
public class ConfirmOrder extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmOrder
     */
    public ConfirmOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlabelKeranjang1 = new javax.swing.JLabel();
        pnlDetailOrder = new javax.swing.JPanel();
        pnlOrderList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblTotalOrderItem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        lblPaymentInfo = new javax.swing.JLabel();
        cmbPaymentInfo = new javax.swing.JComboBox<>();
        btnOrder = new javax.swing.JButton();
        cmbTableInfo = new javax.swing.JComboBox<>();
        lblPaymentInfo1 = new javax.swing.JLabel();

        JlabelKeranjang1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JlabelKeranjang1.setForeground(new java.awt.Color(74, 112, 169));
        JlabelKeranjang1.setText("Detail Order & Payment");

        pnlDetailOrder.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlOrderListLayout = new javax.swing.GroupLayout(pnlOrderList);
        pnlOrderList.setLayout(pnlOrderListLayout);
        pnlOrderListLayout.setHorizontalGroup(
            pnlOrderListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlOrderListLayout.setVerticalGroup(
            pnlOrderListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Total Order Item :");

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lblTotalPrice.setText("0");

        lblTotalOrderItem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTotalOrderItem.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel4.setText("Total Price :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Payment Method:");

        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaymentMethodActionPerformed(evt);
            }
        });

        lblPaymentInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaymentInfo.setText("Payment Info:");

        cmbPaymentInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnOrder.setBackground(new java.awt.Color(74, 112, 169));
        btnOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("Order Now");
        btnOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrder.setDefaultCapable(false);
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderMouseClicked(evt);
            }
        });

        cmbTableInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPaymentInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaymentInfo1.setText("Table Info:");

        javax.swing.GroupLayout pnlDetailOrderLayout = new javax.swing.GroupLayout(pnlDetailOrder);
        pnlDetailOrder.setLayout(pnlDetailOrderLayout);
        pnlDetailOrderLayout.setHorizontalGroup(
            pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOrderList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                        .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotalOrderItem))
                            .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotalPrice))
                            .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                                .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPaymentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPaymentInfo))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPaymentInfo1))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDetailOrderLayout.setVerticalGroup(
            pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrderList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                        .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblTotalOrderItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDetailOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblTotalPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                        .addComponent(lblPaymentInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPaymentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetailOrderLayout.createSequentialGroup()
                        .addComponent(lblPaymentInfo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetailOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlabelKeranjang1)
                        .addGap(939, 939, 939)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JlabelKeranjang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetailOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseClicked
        try {
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Apakah yakin ingin memesan orderan?",
                    "Konfirmasi PEsan",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            if (cmbPaymentInfo.getSelectedItem() == null || cmbPaymentMethod.getSelectedItem() == null) {
                return;
            }

            User thisUser = userController.findByUsername(KF.flayoutCustomer.lblUsername.getText());
            Cart thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());
            if (thisCart == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Keranjang kosong!");
                return;
            }

            List<CartItem> cartItems = cartItemsController.getItemsByCart(thisCart.getCart_id());
            if (cartItems.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Keranjang kosong!");
                return;
            }

            int totalAmount = 0;
            for (CartItem item : cartItems) {
                Product p = productController.getProductById(item.getProduct_id());
                totalAmount += p.getPrice() * item.getQuantity();
            }

            String table = cmbTableInfo.getSelectedItem().toString();

            orderController.addOrder(thisUser.getUser_id(), totalAmount, 0, totalAmount, "Paid", "Waiting", "", table);

            Order thisOrder = orderController.findLastOrderByUser(thisUser.getUser_id());

            for (CartItem item : cartItems) {
                Product p = productController.getProductById(item.getProduct_id());

                int subtotal = p.getPrice() * item.getQuantity();

                orderItemsController.addOrderItem(
                        thisOrder.getOrder_id(),
                        p.getProduct_id(),
                        item.getQuantity(),
                        p.getPrice(),
                        subtotal,
                        ""
                );
            }

            for (CartItem item : cartItems) {
                cartItemsController.deleteCartItem(item.getCart_item_id());
            }

            String method = cmbPaymentMethod.getSelectedItem().toString();
            String info = cmbPaymentInfo.getSelectedItem().toString();

//            paymentcontroller.addPayment(thisOrder.getOrder_id(), method, totalAmount, 0, info);
            Payment payment = PaymentFactory.createPayment(
                    method,
                    thisOrder.getOrder_id(),
                    totalAmount,
                    0,
                    info
            );

            paymentcontroller.addPaymentNew(payment);

            javax.swing.JOptionPane.showMessageDialog(this, "Checkout berhasil! Total: Rp " + totalAmount);

            totalPrice = 0;
            totalitem = 0;

            JPanel pnlUtama = (JPanel) SwingUtilities.getAncestorOfClass(JPanel.class, this);
            KF.UntukPanel(pnlUtama, KF.fdashCustomer);
            KF.fdashCustomer.loadProducts(null);

        } catch (Exception ex) {
            System.getLogger(ConfirmOrder.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_btnOrderMouseClicked

    private void cmbPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentMethodActionPerformed
        Object selected = cmbPaymentMethod.getSelectedItem();
        if (selected != null) {
            String method = selected.toString();

            cmbPaymentInfo.removeAllItems();

            switch (method) {
                case "E-Wallet" -> {
                    cmbPaymentInfo.addItem("GoPay");
                    cmbPaymentInfo.addItem("OVO");
                    cmbPaymentInfo.addItem("Dana");
                    cmbPaymentInfo.setEnabled(true);
                }
                case "Debit" -> {
                    cmbPaymentInfo.addItem("BCA");
                    cmbPaymentInfo.addItem("BNI");
                    cmbPaymentInfo.addItem("Mandiri");
                    cmbPaymentInfo.setEnabled(true);
                }
                case "Cash" -> {
                    cmbPaymentInfo.addItem("-");
                    cmbPaymentInfo.setEnabled(false);
                }
                default ->
                    cmbPaymentInfo.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmbPaymentMethodActionPerformed

    private void setupContainers() {
        JPanel prodContainer = new JPanel();
        prodContainer.setLayout(new BoxLayout(prodContainer, BoxLayout.Y_AXIS));
        prodContainer.setBackground(Color.WHITE);

        prodContainer.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        pnlOrderList.putClientProperty("container", prodContainer);

        JScrollPane scroll = new JScrollPane(prodContainer,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        pnlOrderList.removeAll();
        pnlOrderList.setLayout(new BorderLayout());
        pnlOrderList.add(scroll, BorderLayout.CENTER);
        pnlOrderList.revalidate();
        pnlOrderList.repaint();
    }

    private JPanel createProductCard(Product p, CartItem i) {
        JPanel card = new JPanel();
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
        card.setLayout(new BorderLayout(10, 0)); // 10 px horizontal gap
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120)); // full width
        card.setPreferredSize(new Dimension(pnlOrderList.getWidth() - 20, 120));

        // ===== Image Panel =====
        JPanel imagePanel = new JPanel();
        imagePanel.setPreferredSize(new Dimension(200, 120));
        imagePanel.setBackground(new Color(240, 240, 240));
        imagePanel.setLayout(new GridBagLayout());

        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(JLabel.CENTER);

        if (p.getImage_path() != null && !p.getImage_path().isEmpty()) {
            try {
                File file = new File(p.getImage_path());
                if (file.exists()) {
                    BufferedImage img = ImageIO.read(file);

                    // Resize to fit panel
                    Image scaled = img.getScaledInstance(
                            200, // width
                            120, // height
                            Image.SCALE_SMOOTH
                    );

                    imageLabel.setIcon(new ImageIcon(scaled));
                } else {
                    imageLabel.setText("Image Not Found");
                }
            } catch (Exception e) {
                imageLabel.setText("Error Loading Image");
            }
        } else {
            imageLabel.setText("No Image");
        }

        imageLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        imageLabel.setForeground(new Color(100, 100, 100));

        imagePanel.add(imageLabel);
        card.add(imagePanel, BorderLayout.WEST);

        // ===== Info Panel =====
        JPanel infoPanel = new JPanel();
        infoPanel.setBackground(Color.WHITE);
        infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
        infoPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        int quantity = i.getQuantity();
        int price = p.getPrice();
        int subtotal = quantity * price;

        JLabel lblQty = new JLabel("Qty: " + quantity);
        lblQty.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        JLabel lblName = new JLabel(p.getProduct_name());
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 16));

        JLabel lblPrice = new JLabel("Rp " + price + " x " + quantity + " = Rp " + subtotal);
        lblPrice.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        infoPanel.add(lblQty);
        infoPanel.add(Box.createVerticalStrut(5));
        infoPanel.add(lblName);
        infoPanel.add(Box.createVerticalStrut(5));
        infoPanel.add(lblPrice);

        card.add(infoPanel, BorderLayout.CENTER);

        return card;
    }

    private void loadProducts() {
        try {
            JPanel container = (JPanel) pnlOrderList.getClientProperty("container");
            container.removeAll();

            User thisUser = userController.findByUsername(KF.flayoutCustomer.lblUsername.getText());
            Cart thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());
            if (thisCart == null) {
                return;
            }

            List<CartItem> cartItems = cartItemsController.getItemsByCart(thisCart.getCart_id());

            for (CartItem item : cartItems) {
                Product p = productController.getProductById(item.getProduct_id());
                if (Boolean.TRUE.equals(p.getIs_active())) {
                    container.add(createProductCard(p, item));
                    container.add(Box.createRigidArea(new Dimension(0, 10)));

                    totalitem += item.getQuantity();
                    totalPrice += p.getPrice() * item.getQuantity();
                }
            }

            lblTotalOrderItem.setText(totalitem.toString());
            lblTotalPrice.setText(totalPrice.toString());

            container.revalidate();
            container.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Integer totalPrice = 0;
    private Integer totalitem = 0;

    CartController cartcontroller = CartController.getInstance();
    CartItemsController cartItemsController = CartItemsController.getInstance();
    UserController userController = UserController.getInstance();
    ProductController productController = ProductController.getInstance();
    OrderController orderController = OrderController.getInstance();
    OrderItemsController orderItemsController = OrderItemsController.getInstance();
    PaymentController paymentcontroller = PaymentController.getInstance();

    public void setOrderItem() {
        setupContainers();
        loadProducts();

        cmbPaymentMethod.removeAllItems();
        cmbPaymentMethod.addItem("E-Wallet");
        cmbPaymentMethod.addItem("Debit");
        cmbPaymentMethod.addItem("Cash");

        cmbPaymentInfo.removeAllItems();
        cmbPaymentInfo.setEnabled(false);

        cmbTableInfo.removeAllItems();
        cmbTableInfo.addItem("A1");
        cmbTableInfo.addItem("A2");
        cmbTableInfo.addItem("A3");
        cmbTableInfo.addItem("A4");
        cmbTableInfo.addItem("A5");
        cmbTableInfo.addItem("B1");
        cmbTableInfo.addItem("B2");
        cmbTableInfo.addItem("B3");
        cmbTableInfo.addItem("B4");
        cmbTableInfo.addItem("B5");

        totalPrice = 0;
        totalitem = 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelKeranjang1;
    private javax.swing.JButton btnOrder;
    private javax.swing.JComboBox<String> cmbPaymentInfo;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JComboBox<String> cmbTableInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPaymentInfo;
    private javax.swing.JLabel lblPaymentInfo1;
    private javax.swing.JLabel lblTotalOrderItem;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlDetailOrder;
    private javax.swing.JPanel pnlOrderList;
    // End of variables declaration//GEN-END:variables
}
