/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import app.controller.CartController;
import app.controller.CartItemsController;
import app.controller.OrderController;
import app.controller.OrderItemsController;
import app.controller.PaymentController;
import app.controller.ProductController;
import app.controller.UserController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import models.Cart;
import models.CartItem;
import models.Order;
import models.OrderItems;
import models.Payment;
import models.Product;
import models.User;
import ui.KF;

/**
 *
 * @author RIDHO
 */
public class DetailOrder extends javax.swing.JPanel {

    /**
     * Creates new form DetailOrder
     */
    public DetailOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlOrderList = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        lblTotalOrderItem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalOrderPay = new javax.swing.JLabel();
        lblPaymentStatus = new javax.swing.JLabel();
        lblOrderStatus = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        lblTableNumber = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPaidMethod = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 112, 169));
        jLabel1.setText("Order History");

        pnlOrderList.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlOrderListLayout = new javax.swing.GroupLayout(pnlOrderList);
        pnlOrderList.setLayout(pnlOrderListLayout);
        pnlOrderListLayout.setHorizontalGroup(
            pnlOrderListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlOrderListLayout.setVerticalGroup(
            pnlOrderListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Order Number :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Order Date :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Payment Status :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Order Status :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Total Order Item :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Total Order Payment :");

        lblOrderNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrderNumber.setText("-");

        lblTotalOrderItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalOrderItem.setText("-");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Table Number :");

        lblTotalOrderPay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalOrderPay.setText("-");

        lblPaymentStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaymentStatus.setText("-");

        lblOrderStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOrderStatus.setText("-");

        lblOrderDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOrderDate.setText("-");

        lblTableNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTableNumber.setText("-");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Paid By :");

        lblPaidMethod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPaidMethod.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalOrderItem))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblOrderNumber))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalOrderPay))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPaymentStatus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblOrderStatus)))
                .addGap(594, 594, 594)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblOrderDate))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblTableNumber))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblPaidMethod)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblOrderNumber)
                    .addComponent(lblOrderDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalOrderItem)
                    .addComponent(jLabel8)
                    .addComponent(lblTableNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTotalOrderPay)
                    .addComponent(jLabel9)
                    .addComponent(lblPaidMethod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblPaymentStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblOrderStatus))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlOrderList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlOrderList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setupContainers() {
        JPanel prodContainer = new JPanel();
        prodContainer.setLayout(new BoxLayout(prodContainer, BoxLayout.Y_AXIS));
        prodContainer.setBackground(Color.WHITE);

        prodContainer.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        pnlOrderList.putClientProperty("container", prodContainer);

        JScrollPane scroll = new JScrollPane(prodContainer,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        pnlOrderList.removeAll();
        pnlOrderList.setLayout(new BorderLayout());
        pnlOrderList.add(scroll, BorderLayout.CENTER);
        pnlOrderList.revalidate();
        pnlOrderList.repaint();
    }

    private JPanel createProductCard(Product p, OrderItems i) {
        JPanel card = new JPanel();
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
        card.setLayout(new BorderLayout(10, 0)); // 10 px horizontal gap
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120)); // full width
        card.setPreferredSize(new Dimension(pnlOrderList.getWidth() - 20, 120));

        // ===== Image Panel =====
        JPanel imagePanel = new JPanel();
        imagePanel.setPreferredSize(new Dimension(200, 120));
        imagePanel.setBackground(new Color(240, 240, 240));
        imagePanel.setLayout(new GridBagLayout());

        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(JLabel.CENTER);

        if (p.getImage_path() != null && !p.getImage_path().isEmpty()) {
            try {
                File file = new File(p.getImage_path());
                if (file.exists()) {
                    BufferedImage img = ImageIO.read(file);

                    // Resize to fit panel
                    Image scaled = img.getScaledInstance(
                            200, // width
                            120, // height
                            Image.SCALE_SMOOTH
                    );

                    imageLabel.setIcon(new ImageIcon(scaled));
                } else {
                    imageLabel.setText("Image Not Found");
                }
            } catch (Exception e) {
                imageLabel.setText("Error Loading Image");
            }
        } else {
            imageLabel.setText("No Image");
        }

        imageLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        imageLabel.setForeground(new Color(100, 100, 100));

        imagePanel.add(imageLabel);
        card.add(imagePanel, BorderLayout.WEST);

        // ===== Info Panel =====
        JPanel infoPanel = new JPanel();
        infoPanel.setBackground(Color.WHITE);
        infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
        infoPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        int quantity = i.getQuantity();
        int price = p.getPrice();
        int subtotal = quantity * price;

        JLabel lblQty = new JLabel("Qty: " + quantity);
        lblQty.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        JLabel lblName = new JLabel(p.getProduct_name());
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 16));

        JLabel lblPrice = new JLabel("Rp " + price + " x " + quantity + " = Rp " + subtotal);
        lblPrice.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        infoPanel.add(lblQty);
        infoPanel.add(Box.createVerticalStrut(5));
        infoPanel.add(lblName);
        infoPanel.add(Box.createVerticalStrut(5));
        infoPanel.add(lblPrice);

        card.add(infoPanel, BorderLayout.CENTER);

        return card;
    }

    private void loadProducts(Integer order_id) {
        try {
            JPanel container = (JPanel) pnlOrderList.getClientProperty("container");
            container.removeAll();
            
            Order thisOrder = orderController.findOrderById(order_id);
            if (thisOrder == null) {
                return;
            }

            List<OrderItems> orderItems = orderItemsController.getItemsByOrderId(thisOrder.getOrder_id());

            for (OrderItems item : orderItems) {
                Product p = productController.getProductById(item.getProduct_id());
                if (Boolean.TRUE.equals(p.getIs_active())) {
                    container.add(createProductCard(p, item));
                    container.add(Box.createRigidArea(new Dimension(0, 10)));

                    totalitem += item.getQuantity();
                }
            }
            
            lblTotalOrderItem.setText(totalitem.toString());

            container.revalidate();
            container.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Integer totalitem = 0;

    ProductController productController = ProductController.getInstance();
    OrderController orderController = OrderController.getInstance();
    OrderItemsController orderItemsController = OrderItemsController.getInstance();
    PaymentController paymentcontroller = PaymentController.getInstance();

    public void setOrderItem(Integer order_id) {
        try {
            setupContainers();
            loadProducts(order_id);
            
            totalitem = 0;
            
            Order thisOrder = orderController.findOrderById(order_id);
            
            lblOrderNumber.setText(thisOrder.getOrderCode());
            lblOrderDate.setText(thisOrder.getOrder_date().toString());
            lblTotalOrderPay.setText("Rp. " + thisOrder.getFinal_amount().toString());
            lblPaymentStatus.setText(thisOrder.getPayment_status());
            lblOrderStatus.setText(thisOrder.getOrder_status());
            lblTableNumber.setText(thisOrder.getTableCode());
            
            Payment thisPayment = paymentcontroller.findByOrderId(order_id);
            
            lblPaidMethod.setText(thisPayment.getPayment_method() + " " + thisPayment.getInfoPayment());
            
        } catch (Exception ex) {
            System.getLogger(DetailOrder.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblOrderStatus;
    private javax.swing.JLabel lblPaidMethod;
    private javax.swing.JLabel lblPaymentStatus;
    private javax.swing.JLabel lblTableNumber;
    private javax.swing.JLabel lblTotalOrderItem;
    private javax.swing.JLabel lblTotalOrderPay;
    private javax.swing.JPanel pnlOrderList;
    // End of variables declaration//GEN-END:variables
}
