/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import app.controller.CartController;
import app.controller.CartItemsController;
import app.controller.ProductController;
import app.controller.UserController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import models.Cart;
import models.Product;
import models.User;
import ui.KF;

/**
 *
 * @author Dell
 */
public class DetailProductCustomer extends javax.swing.JPanel {

    /**
     * Creates new form DetailProductCustomer
     */
    private Product product;

    public DetailProductCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblTitleDesc = new javax.swing.JLabel();
        btnMinus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        btnAddCart = new javax.swing.JButton();
        lblDesc1 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 112, 169));
        jLabel1.setText("Detail Product");

        jPanel2.setPreferredSize(new java.awt.Dimension(450, 300));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("No Image");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        lblProductName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblProductName.setText("Product Name");

        lblTitleDesc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleDesc.setText("Description:");

        btnMinus.setBackground(new java.awt.Color(239, 236, 227));
        btnMinus.setText("-");
        btnMinus.setBorderPainted(false);
        btnMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusMouseClicked(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(239, 236, 227));
        btnAdd.setText("+");
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setText("0");

        btnAddCart.setBackground(new java.awt.Color(74, 112, 169));
        btnAddCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCart.setText("Add to Cart");
        btnAddCart.setBorderPainted(false);
        btnAddCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCartMouseClicked(evt);
            }
        });

        lblDesc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDesc1.setText("Stock: ");

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStock.setText("0");

        lblDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDesc.setText("Product Desc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQty)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddCart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleDesc)
                            .addComponent(lblProductName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDesc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStock))
                            .addComponent(lblDesc))))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProductName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesc1)
                            .addComponent(lblStock))
                        .addGap(39, 39, 39)
                        .addComponent(lblTitleDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDesc))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQty))
                .addGap(18, 18, 18)
                .addComponent(btnAddCart, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    CartController cartcontroller = CartController.getInstance();
    CartItemsController caritemcontroller = CartItemsController.getInstance();
    UserController usercontroller = UserController.getInstance();
    ProductController productcontroler = ProductController.getInstance();

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        int stock = Integer.parseInt(lblStock.getText()); // ambil stock
        if (this.qty < stock) {
            this.qty++;
            loadQty();
        } else {
            JOptionPane.showMessageDialog(this, "Qty tidak boleh lebih dari stock");
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseClicked
        if (this.qty > 1) {
            this.qty--;
            loadQty();
        } else {
            JOptionPane.showMessageDialog(this, "Qty tidak boleh kurang dari 1");
        }
    }//GEN-LAST:event_btnMinusMouseClicked

    private void btnAddCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCartMouseClicked
        try {
            User thisUser = usercontroller.findByUsername(KF.flayoutCustomer.lblUsername.getText());
            Cart thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());

            if (thisCart == null) {
                cartcontroller.createCart(thisUser.getUser_id());
                thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());
            }

            Product thisProduct = productcontroler.getProductByName(lblProductName.getText());
            Integer newqty = thisProduct.getStock() - Integer.valueOf(lblQty.getText());
            thisProduct.setStock(newqty);
            productcontroler.updateStock(thisProduct.getProduct_id(), newqty);
            
            caritemcontroller.insertCartItem(thisCart.getCart_id(), thisProduct.getProduct_id(), Integer.valueOf(lblQty.getText()));

            JOptionPane.showMessageDialog(this, "Input Success!",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
            loadData(thisProduct);
            
            JPanel pnlUtama = (JPanel) SwingUtilities.getAncestorOfClass(JPanel.class, this);
            KF.UntukPanel(pnlUtama, KF.fkeranjang);
            KF.fkeranjang.setKeranjang();
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menambahkan ke cart: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAddCartMouseClicked

    private Integer qty = 1;

    public void loadQty() {
        lblQty.setText(this.qty.toString());
    }

    private void loadImage(String imagePath) {
        try {
            ImageIcon icon = null;

            URL resource = getClass().getResource("/" + imagePath);
            if (resource != null) {
                icon = new ImageIcon(resource);
            } else {
                File file = new File(imagePath);
                if (file.exists()) {
                    icon = new ImageIcon(file.getAbsolutePath());
                }
            }

            if (icon != null) {
                Image scaled = icon.getImage().getScaledInstance(450, 300, Image.SCALE_SMOOTH);
                lblImage.setIcon(new ImageIcon(scaled));
                lblImage.setText("");
            } else {
                lblImage.setText("No Image");
                lblImage.setIcon(null);
            }

        } catch (Exception e) {
            lblImage.setText("No Image");
            lblImage.setIcon(null);
            System.out.println("Gagal load gambar: " + e.getMessage());
        }
    }

    public void loadData(Product p) {
        lblProductName.setText(p.getProduct_name());
        lblDesc.setText(p.getDescription());
        lblQty.setText(this.qty.toString());
        lblStock.setText(p.getStock().toString());
        this.qty = 1;
        if (p.getImage_path() != null) {
            loadImage(p.getImage_path());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnMinus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDesc1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitleDesc;
    // End of variables declaration//GEN-END:variables
}
