/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import app.controller.CartController;
import app.controller.CartItemsController;
import app.controller.ProductController;
import app.controller.UserController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import models.Cart;
import models.CartItem;
import models.Category;
import models.Product;
import models.User;
import ui.KF;
import util.WrapLayout;

/**
 *
 * @author RIDHO
 */
public class KeranjangCustomer extends javax.swing.JPanel {

    /**
     * Creates new form KeranjangCustomer
     */
    public KeranjangCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainerCart = new javax.swing.JPanel();
        pnlkeranjang1 = new javax.swing.JPanel();
        btnCheckout = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JlabelKeranjang1 = new javax.swing.JLabel();

        pnlContainerCart.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout pnlContainerCartLayout = new javax.swing.GroupLayout(pnlContainerCart);
        pnlContainerCart.setLayout(pnlContainerCartLayout);
        pnlContainerCartLayout.setHorizontalGroup(
            pnlContainerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        pnlContainerCartLayout.setVerticalGroup(
            pnlContainerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        pnlkeranjang1.setBackground(new java.awt.Color(255, 255, 255));

        btnCheckout.setText("Checkout");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Total: Rp.");

        javax.swing.GroupLayout pnlkeranjang1Layout = new javax.swing.GroupLayout(pnlkeranjang1);
        pnlkeranjang1.setLayout(pnlkeranjang1Layout);
        pnlkeranjang1Layout.setHorizontalGroup(
            pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkeranjang1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCheckout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 700, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addGap(176, 176, 176))
            .addGroup(pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkeranjang1Layout.createSequentialGroup()
                    .addContainerGap(706, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(202, 202, 202)))
        );
        pnlkeranjang1Layout.setVerticalGroup(
            pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkeranjang1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlkeranjang1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        JlabelKeranjang1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JlabelKeranjang1.setForeground(new java.awt.Color(74, 112, 169));
        JlabelKeranjang1.setText("Keranjang Produk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContainerCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlkeranjang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(JlabelKeranjang1)
                    .addContainerGap(851, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(pnlContainerCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlkeranjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(JlabelKeranjang1)
                    .addContainerGap(748, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setupContainers() {
        // Panel utama menumpuk vertikal
        JPanel prodContainer = new JPanel();
        prodContainer.setLayout(new BoxLayout(prodContainer, BoxLayout.Y_AXIS));
        prodContainer.setBackground(Color.WHITE);

        // kasih jarak antar card
        prodContainer.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // simpan sebagai client property agar loadProducts bisa akses
        pnlContainerCart.putClientProperty("container", prodContainer);

        // ScrollPane untuk scroll vertical
        JScrollPane scroll = new JScrollPane(prodContainer,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        pnlContainerCart.removeAll();
        pnlContainerCart.setLayout(new BorderLayout());
        pnlContainerCart.add(scroll, BorderLayout.CENTER);
        pnlContainerCart.revalidate();
        pnlContainerCart.repaint();
    }

    private JPanel createProductCard(Product p, CartItem i) {
        JPanel card = new JPanel();
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
        card.setLayout(new BorderLayout(10, 0)); // 10 px horizontal gap
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120)); // full width
        card.setPreferredSize(new Dimension(pnlContainerCart.getWidth() - 20, 120));

        // ===== Image Panel =====
        JPanel imagePanel = new JPanel();
        imagePanel.setPreferredSize(new Dimension(120, 120));
        imagePanel.setBackground(new Color(240, 240, 240));
        imagePanel.setLayout(new GridBagLayout());

        JLabel lblImage = new JLabel("No Image"); // bisa diganti ImageIcon nanti
        lblImage.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblImage.setForeground(new Color(100, 100, 100));
        imagePanel.add(lblImage);

        card.add(imagePanel, BorderLayout.WEST);

        // ===== Info Panel =====
        JPanel infoPanel = new JPanel();
        infoPanel.setBackground(Color.WHITE);
        infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
        infoPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JLabel lblQty = new JLabel("Qty: " + i.getQuantity());
        lblQty.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        JLabel lblName = new JLabel(p.getProduct_name());
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 16));

        JLabel lblPrice = new JLabel("Rp " + p.getPrice());
        lblPrice.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        infoPanel.add(lblQty);
        infoPanel.add(Box.createVerticalStrut(5)); // jarak antar label
        infoPanel.add(lblName);
        infoPanel.add(Box.createVerticalStrut(5));
        infoPanel.add(lblPrice);

        card.add(infoPanel, BorderLayout.CENTER);

        // ===== Button Panel =====
        JButton btnDelete = new JButton("Delete");
        btnDelete.setFocusPainted(false);
        btnDelete.setBackground(new Color(240, 80, 80));
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setPreferredSize(new Dimension(80, 40));
        btnDelete.addActionListener(e -> {
            // TODO: hapus item dari cart
        });

        JPanel btnPanel = new JPanel();
        btnPanel.setBackground(Color.WHITE);
        btnPanel.setLayout(new GridBagLayout()); // supaya tombol tetap di tengah vertikal
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 10, 0, 10);
        btnPanel.add(btnDelete, gbc);

        card.add(btnPanel, BorderLayout.EAST);

        return card;
    }

    private void loadProducts() {
        try {
            JPanel container = (JPanel) pnlContainerCart.getClientProperty("container");
            container.removeAll();

            User thisUser = userController.findByUsername(KF.flayoutCustomer.lblUsername.getText());
            Cart thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());
            if (thisCart == null) {
                return;
            }

            List<CartItem> cartItems = cartItemsController.getItemsByCart(thisCart.getCart_id());

            for (CartItem item : cartItems) {
                Product p = productController.getProductById(item.getProduct_id());
                if (Boolean.TRUE.equals(p.getIs_active())) {
                    container.add(createProductCard(p, item));
                    container.add(Box.createRigidArea(new Dimension(0, 10))); // jarak antar card
                }
            }

            container.revalidate();
            container.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    CartController cartcontroller = CartController.getInstance();
    CartItemsController cartItemsController = CartItemsController.getInstance();
    UserController userController = UserController.getInstance();
    ProductController productController = ProductController.getInstance();

    public void setUser() {
        setupContainers();
        loadProducts();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelKeranjang1;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlContainerCart;
    private javax.swing.JPanel pnlkeranjang1;
    // End of variables declaration//GEN-END:variables
}
