/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import app.controller.CartController;
import app.controller.CartItemsController;
import app.controller.OrderController;
import app.controller.OrderItemsController;
import app.controller.ProductController;
import app.controller.UserController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import models.Cart;
import models.CartItem;
import models.Category;
import models.Order;
import models.Product;
import models.User;
import ui.KF;
import util.WrapLayout;

/**
 *
 * @author RIDHO
 */
public class KeranjangCustomer extends javax.swing.JPanel {

    /**
     * Creates new form KeranjangCustomer
     */
    public KeranjangCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainerCart = new javax.swing.JPanel();
        pnlkeranjang1 = new javax.swing.JPanel();
        btnCheckout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        JlabelKeranjang1 = new javax.swing.JLabel();

        pnlContainerCart.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContainerCartLayout = new javax.swing.GroupLayout(pnlContainerCart);
        pnlContainerCart.setLayout(pnlContainerCartLayout);
        pnlContainerCartLayout.setHorizontalGroup(
            pnlContainerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContainerCartLayout.setVerticalGroup(
            pnlContainerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        pnlkeranjang1.setBackground(new java.awt.Color(74, 112, 169));

        btnCheckout.setBackground(new java.awt.Color(239, 236, 227));
        btnCheckout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCheckout.setText("Order");
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total: Rp.");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0");

        javax.swing.GroupLayout pnlkeranjang1Layout = new javax.swing.GroupLayout(pnlkeranjang1);
        pnlkeranjang1.setLayout(pnlkeranjang1Layout);
        pnlkeranjang1Layout.setHorizontalGroup(
            pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkeranjang1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlkeranjang1Layout.setVerticalGroup(
            pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkeranjang1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlkeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JlabelKeranjang1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JlabelKeranjang1.setForeground(new java.awt.Color(74, 112, 169));
        JlabelKeranjang1.setText("Keranjang Produk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlkeranjang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContainerCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlabelKeranjang1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JlabelKeranjang1)
                .addGap(18, 18, 18)
                .addComponent(pnlContainerCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlkeranjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
        try {
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Apakah yakin ingin memesan orderan?",
                    "Konfirmasi PEsan",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            User thisUser = userController.findByUsername(KF.flayoutCustomer.lblUsername.getText());
            Cart thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());
            if (thisCart == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Keranjang kosong!");
                return;
            }

            List<CartItem> cartItems = cartItemsController.getItemsByCart(thisCart.getCart_id());
            if (cartItems.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Keranjang kosong!");
                return;
            }

            JPanel pnlUtama = (JPanel) SwingUtilities.getAncestorOfClass(JPanel.class, this);
            KF.UntukPanel(pnlUtama, KF.forderpayment);
            KF.forderpayment.setOrderItem();

            loadProducts();
        } catch (Exception ex) {
            System.getLogger(KeranjangCustomer.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void setupContainers() {
        JPanel prodContainer = new JPanel();
        prodContainer.setLayout(new BoxLayout(prodContainer, BoxLayout.Y_AXIS));
        prodContainer.setBackground(Color.WHITE);

        prodContainer.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        pnlContainerCart.putClientProperty("container", prodContainer);

        JScrollPane scroll = new JScrollPane(prodContainer,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        pnlContainerCart.removeAll();
        pnlContainerCart.setLayout(new BorderLayout());
        pnlContainerCart.add(scroll, BorderLayout.CENTER);
        pnlContainerCart.revalidate();
        pnlContainerCart.repaint();
    }

    private JPanel createProductCard(Product p, CartItem i) {
        JPanel card = new JPanel();
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
        card.setLayout(new BorderLayout(10, 0)); // 10 px horizontal gap
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120)); // full width
        card.setPreferredSize(new Dimension(pnlContainerCart.getWidth() - 20, 120));

        // ===== Image Panel =====
        JPanel imagePanel = new JPanel();
        imagePanel.setPreferredSize(new Dimension(200, 120));
        imagePanel.setBackground(new Color(240, 240, 240));
        imagePanel.setLayout(new GridBagLayout());

        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(JLabel.CENTER);

        if (p.getImage_path() != null && !p.getImage_path().isEmpty()) {
            try {
                File file = new File(p.getImage_path());
                if (file.exists()) {
                    BufferedImage img = ImageIO.read(file);

                    // Resize to fit panel
                    Image scaled = img.getScaledInstance(
                            200, // width
                            120, // height
                            Image.SCALE_SMOOTH
                    );

                    imageLabel.setIcon(new ImageIcon(scaled));
                } else {
                    imageLabel.setText("Image Not Found");
                }
            } catch (Exception e) {
                imageLabel.setText("Error Loading Image");
            }
        } else {
            imageLabel.setText("No Image");
        }

        imageLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        imageLabel.setForeground(new Color(100, 100, 100));

        imagePanel.add(imageLabel);
        card.add(imagePanel, BorderLayout.WEST);

        // ===== Info Panel =====
        JPanel infoPanel = new JPanel();
        infoPanel.setBackground(Color.WHITE);
        infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
        infoPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        int quantity = i.getQuantity();
        int price = p.getPrice();
        int subtotal = quantity * price;

        JLabel lblQty = new JLabel("Qty: " + quantity);
        lblQty.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        JLabel lblName = new JLabel(p.getProduct_name());
        lblName.setFont(new Font("Segoe UI", Font.BOLD, 16));

        JLabel lblPrice = new JLabel("Rp " + price + " x " + quantity + " = Rp " + subtotal);
        lblPrice.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        infoPanel.add(lblQty);
        infoPanel.add(Box.createVerticalStrut(5));
        infoPanel.add(lblName);
        infoPanel.add(Box.createVerticalStrut(5));
        infoPanel.add(lblPrice);

        card.add(infoPanel, BorderLayout.CENTER);

        // ===== Button Panel =====
        JButton btnDelete = new JButton("Delete");
        btnDelete.setFocusPainted(false);
        btnDelete.setBackground(new Color(240, 80, 80));
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setPreferredSize(new Dimension(80, 40));
        btnDelete.addActionListener(e -> {
            try {

                int confirm = JOptionPane.showConfirmDialog(
                        this,
                        "Yakin ingin menghapus item ini dari keranjang?",
                        "Konfirmasi Hapus",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                }

                cartItemsController.deleteCartItem(i.getCart_item_id());
                Integer newStock = p.getStock() + quantity;
                productController.updateStock(p.getProduct_id(), newStock);

                setKeranjang();
            } catch (Exception ex) {
                System.getLogger(KeranjangCustomer.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });

        JPanel btnPanel = new JPanel();
        btnPanel.setBackground(Color.WHITE);
        btnPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 10, 0, 10);
        btnPanel.add(btnDelete, gbc);

        card.add(btnPanel, BorderLayout.EAST);

        return card;
    }

    private void loadProducts() {
        try {
            JPanel container = (JPanel) pnlContainerCart.getClientProperty("container");
            container.removeAll();

            User thisUser = userController.findByUsername(KF.flayoutCustomer.lblUsername.getText());
            Cart thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());
            if (thisCart == null) {
                return;
            }

            List<CartItem> cartItems = cartItemsController.getItemsByCart(thisCart.getCart_id());

            for (CartItem item : cartItems) {
                Product p = productController.getProductById(item.getProduct_id());
                if (Boolean.TRUE.equals(p.getIs_active())) {
                    container.add(createProductCard(p, item));
                    container.add(Box.createRigidArea(new Dimension(0, 10)));

                    totalPrice += p.getPrice() * item.getQuantity();
                }
            }

            lblTotal.setText(totalPrice.toString());

            container.revalidate();
            container.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Integer totalPrice = 0;

    CartController cartcontroller = CartController.getInstance();
    CartItemsController cartItemsController = CartItemsController.getInstance();
    UserController userController = UserController.getInstance();
    ProductController productController = ProductController.getInstance();
    OrderController orderController = OrderController.getInstance();
    OrderItemsController orderItemsController = OrderItemsController.getInstance();

    public void setKeranjang() {
        setupContainers();
        loadProducts();

        totalPrice = 0;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelKeranjang1;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlContainerCart;
    private javax.swing.JPanel pnlkeranjang1;
    // End of variables declaration//GEN-END:variables
}
