/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import app.controller.CartController;
import app.controller.CartItemsController;
import app.controller.OrderController;
import app.controller.OrderItemsController;
import app.controller.PaymentController;
import app.controller.ProductController;
import app.controller.UserController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import models.Cart;
import models.CartItem;
import models.Order;
import models.Payment;
import models.Product;
import models.User;
import ui.KF;

/**
 *
 * @author RIDHO
 */
public class OrderMenu extends javax.swing.JPanel {

    /**
     * Creates new form OrderMenu
     */
    public OrderMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlContainerOrder = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 112, 169));
        jLabel1.setText("Order History");

        pnlContainerOrder.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContainerOrderLayout = new javax.swing.GroupLayout(pnlContainerOrder);
        pnlContainerOrder.setLayout(pnlContainerOrderLayout);
        pnlContainerOrderLayout.setHorizontalGroup(
            pnlContainerOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1183, Short.MAX_VALUE)
        );
        pnlContainerOrderLayout.setVerticalGroup(
            pnlContainerOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContainerOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlContainerOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setupContainers() {
        JPanel prodContainer = new JPanel();
        prodContainer.setLayout(new BoxLayout(prodContainer, BoxLayout.Y_AXIS));
        prodContainer.setBackground(Color.WHITE);

        prodContainer.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        pnlContainerOrder.putClientProperty("container", prodContainer);

        JScrollPane scroll = new JScrollPane(prodContainer,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        pnlContainerOrder.removeAll();
        pnlContainerOrder.setLayout(new BorderLayout());
        pnlContainerOrder.add(scroll, BorderLayout.CENTER);
        pnlContainerOrder.revalidate();
        pnlContainerOrder.repaint();
    }

    private JPanel createOrderCard(Order o, Payment p) {
        JPanel card = new JPanel();
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
        card.setLayout(new BorderLayout(10, 0)); // 10 px horizontal gap
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120)); // full width
        card.setPreferredSize(new Dimension(pnlContainerOrder.getWidth() - 20, 120));

        // ===== Info Panel =====
        JPanel infoPanel = new JPanel();
        infoPanel.setBackground(Color.WHITE);
        infoPanel.setLayout(new GridBagLayout());
        infoPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 0);
        JLabel lblOrderCode = new JLabel("Order Code: " + o.getOrderCode());
        lblOrderCode.setFont(new Font("Segoe UI", Font.BOLD, 18));
        infoPanel.add(lblOrderCode, gbc);

        gbc.gridy++;
        JLabel lblOrderDate = new JLabel("Order Date: " + o.getOrder_date().toString());
        lblOrderDate.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        infoPanel.add(lblOrderDate, gbc);

        gbc.gridy++;
        JLabel lblPrice = new JLabel("Rp. " + o.getFinal_amount().toString());
        lblPrice.setFont(new Font("Segoe UI", Font.BOLD, 18));
        infoPanel.add(lblPrice, gbc);

        // ===== Status Panel =====
        JLabel lblPaymentStatus = new JLabel("Payment Status: " + o.getPayment_status());
        lblPaymentStatus.setFont(new Font("Segoe UI", Font.BOLD, 14));
        Color statusColor;
        switch (o.getPayment_status().toLowerCase()) {
            case "paid":
                statusColor = new Color(46, 204, 113);
                break;
            case "pending":
                statusColor = new Color(241, 196, 15);
                break;
            case "failed":
                statusColor = new Color(231, 76, 60);
                break;
            case "cancelled":
                statusColor = new Color(231, 76, 60);
                break;
            default:
                statusColor = Color.GRAY;
        }

        lblPaymentStatus.setForeground(statusColor);

        JLabel lblOrderStatus = new JLabel("Order Status: " + o.getOrder_status());
        lblOrderStatus.setFont(new Font("Segoe UI", Font.BOLD, 18));

        switch (o.getOrder_status().toLowerCase()) {
            case "completed":
                lblOrderStatus.setForeground(new Color(46, 204, 113));
                break;
            case "processing":
                lblOrderStatus.setForeground(new Color(52, 152, 219));
                break;
            case "cancelled":
                lblOrderStatus.setForeground(new Color(231, 76, 60));
                break;
            case "waiting":
                lblOrderStatus.setForeground(new Color(74, 112, 169));
                break;
            default:
                lblOrderStatus.setForeground(Color.DARK_GRAY);
        }

        JPanel statusPanel = new JPanel();
        statusPanel.setBackground(Color.WHITE);
        statusPanel.setLayout(new BoxLayout(statusPanel, BoxLayout.Y_AXIS));
        statusPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 10));

        statusPanel.add(lblPaymentStatus);
        statusPanel.add(Box.createVerticalStrut(5));
        statusPanel.add(lblOrderStatus);

        // ===== Masukkan ke card =====
        card.add(infoPanel, BorderLayout.WEST);
        card.add(statusPanel, BorderLayout.EAST);

        // ===== Button Panel =====
        JButton btnView = new JButton("View");
        btnView.setFocusPainted(false);
        btnView.setBackground(new Color(74, 112, 169));
        btnView.setForeground(Color.WHITE);
        btnView.setPreferredSize(new Dimension(80, 40));
        btnView.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnView.addActionListener(e -> {
            try {
                JPanel pnlUtama = (JPanel) SwingUtilities.getAncestorOfClass(JPanel.class, this);
                KF.UntukPanel(pnlUtama, KF.fdetailorder);
                KF.fdetailorder.setOrderItem(o.getOrder_id());

            } catch (Exception ex) {
                System.getLogger(KeranjangCustomer.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });

        JPanel btnPanel = new JPanel();
        btnPanel.setBackground(Color.WHITE);
        btnPanel.setLayout(new GridBagLayout());
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 10, 0, 10);
        btnPanel.add(btnView, gbc);

        JPanel rightPanel = new JPanel();
        rightPanel.setBackground(Color.WHITE);
        rightPanel.setLayout(new BoxLayout(rightPanel, BoxLayout.X_AXIS));

        rightPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        rightPanel.add(statusPanel);
        rightPanel.add(Box.createHorizontalStrut(20));

        rightPanel.add(btnPanel);

        card.add(rightPanel, BorderLayout.EAST);

        return card;
    }

    private void loadOrder() {
        try {
            JPanel container = (JPanel) pnlContainerOrder.getClientProperty("container");
            container.removeAll();

            User thisUser = userController.findByUsername(KF.flayoutCustomer.lblUsername.getText());
            Cart thisCart = cartcontroller.getCartByUser(thisUser.getUser_id());
            if (thisCart == null) {
                return;
            }

            List<Order> orderList = orderController.getOrdersByUserId(thisUser.getUser_id());

            for (Order item : orderList) {
                Payment thisPayment = paymentcont.findByOrderId(item.getOrder_id());
                container.add(createOrderCard(item, thisPayment));
                container.add(Box.createRigidArea(new Dimension(0, 10)));

            }

            container.revalidate();
            container.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    CartController cartcontroller = CartController.getInstance();
    CartItemsController cartItemsController = CartItemsController.getInstance();
    UserController userController = UserController.getInstance();
    ProductController productController = ProductController.getInstance();
    OrderController orderController = OrderController.getInstance();
    OrderItemsController orderItemsController = OrderItemsController.getInstance();
    PaymentController paymentcont = PaymentController.getInstance();

    public void setKeranjang() {
        setupContainers();
        loadOrder();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlContainerOrder;
    // End of variables declaration//GEN-END:variables
}
